import type { TaskDefinition } from './types';

export const TASK_DEFINITIONS: TaskDefinition[] = [
  // ── Mathematics ──────────────────────────────────────────────────────────
  // Chapter 1: Algebra
  {
    id: 'task-math-1-1',
    subjectId: 'subj-math',
    chapterId: 'chap-math-1',
    title: 'Solve linear equations',
    subjectName: 'Mathematics',
    chapterName: 'Algebra',
  },
  {
    id: 'task-math-1-2',
    subjectId: 'subj-math',
    chapterId: 'chap-math-1',
    title: 'Quadratic formula',
    subjectName: 'Mathematics',
    chapterName: 'Algebra',
  },
  {
    id: 'task-math-1-3',
    subjectId: 'subj-math',
    chapterId: 'chap-math-1',
    title: 'Systems of equations',
    subjectName: 'Mathematics',
    chapterName: 'Algebra',
  },
  // Chapter 2: Geometry
  {
    id: 'task-math-2-1',
    subjectId: 'subj-math',
    chapterId: 'chap-math-2',
    title: 'Area and perimeter',
    subjectName: 'Mathematics',
    chapterName: 'Geometry',
  },
  {
    id: 'task-math-2-2',
    subjectId: 'subj-math',
    chapterId: 'chap-math-2',
    title: 'Triangles and angles',
    subjectName: 'Mathematics',
    chapterName: 'Geometry',
  },
  {
    id: 'task-math-2-3',
    subjectId: 'subj-math',
    chapterId: 'chap-math-2',
    title: 'Circles and arcs',
    subjectName: 'Mathematics',
    chapterName: 'Geometry',
  },
  // Chapter 3: Statistics
  {
    id: 'task-math-3-1',
    subjectId: 'subj-math',
    chapterId: 'chap-math-3',
    title: 'Mean, median and mode',
    subjectName: 'Mathematics',
    chapterName: 'Statistics',
  },
  {
    id: 'task-math-3-2',
    subjectId: 'subj-math',
    chapterId: 'chap-math-3',
    title: 'Probability basics',
    subjectName: 'Mathematics',
    chapterName: 'Statistics',
  },
  {
    id: 'task-math-3-3',
    subjectId: 'subj-math',
    chapterId: 'chap-math-3',
    title: 'Reading data graphs',
    subjectName: 'Mathematics',
    chapterName: 'Statistics',
  },
  // ── Science ───────────────────────────────────────────────────────────────
  // Chapter 1: Physics
  {
    id: 'task-sci-1-1',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-1',
    title: "Newton's laws of motion",
    subjectName: 'Science',
    chapterName: 'Physics',
  },
  {
    id: 'task-sci-1-2',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-1',
    title: 'Energy and work',
    subjectName: 'Science',
    chapterName: 'Physics',
  },
  {
    id: 'task-sci-1-3',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-1',
    title: 'Waves and sound',
    subjectName: 'Science',
    chapterName: 'Physics',
  },
  // Chapter 2: Chemistry
  {
    id: 'task-sci-2-1',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-2',
    title: 'Periodic table basics',
    subjectName: 'Science',
    chapterName: 'Chemistry',
  },
  {
    id: 'task-sci-2-2',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-2',
    title: 'Chemical bonds',
    subjectName: 'Science',
    chapterName: 'Chemistry',
  },
  {
    id: 'task-sci-2-3',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-2',
    title: 'Reactions and equations',
    subjectName: 'Science',
    chapterName: 'Chemistry',
  },
  // Chapter 3: Biology
  {
    id: 'task-sci-3-1',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-3',
    title: 'Cell structure',
    subjectName: 'Science',
    chapterName: 'Biology',
  },
  {
    id: 'task-sci-3-2',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-3',
    title: 'Photosynthesis',
    subjectName: 'Science',
    chapterName: 'Biology',
  },
  {
    id: 'task-sci-3-3',
    subjectId: 'subj-sci',
    chapterId: 'chap-sci-3',
    title: 'Human body systems',
    subjectName: 'Science',
    chapterName: 'Biology',
  },
  // ── English ───────────────────────────────────────────────────────────────
  // Chapter 1: Grammar
  {
    id: 'task-eng-1-1',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-1',
    title: 'Parts of speech',
    subjectName: 'English',
    chapterName: 'Grammar',
  },
  {
    id: 'task-eng-1-2',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-1',
    title: 'Sentence structure',
    subjectName: 'English',
    chapterName: 'Grammar',
  },
  {
    id: 'task-eng-1-3',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-1',
    title: 'Punctuation rules',
    subjectName: 'English',
    chapterName: 'Grammar',
  },
  // Chapter 2: Literature
  {
    id: 'task-eng-2-1',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-2',
    title: 'Story elements',
    subjectName: 'English',
    chapterName: 'Literature',
  },
  {
    id: 'task-eng-2-2',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-2',
    title: 'Poetry analysis',
    subjectName: 'English',
    chapterName: 'Literature',
  },
  {
    id: 'task-eng-2-3',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-2',
    title: 'Character development',
    subjectName: 'English',
    chapterName: 'Literature',
  },
  // Chapter 3: Writing
  {
    id: 'task-eng-3-1',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-3',
    title: 'Essay structure',
    subjectName: 'English',
    chapterName: 'Writing',
  },
  {
    id: 'task-eng-3-2',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-3',
    title: 'Paragraph writing',
    subjectName: 'English',
    chapterName: 'Writing',
  },
  {
    id: 'task-eng-3-3',
    subjectId: 'subj-eng',
    chapterId: 'chap-eng-3',
    title: 'Editing and revision',
    subjectName: 'English',
    chapterName: 'Writing',
  },
];
